#!/bin/env bash

# First setup unload_rds.properties (example in unload_rds.properties.template) then run this script
# $1 is "-h" or the directory to dump the RDS to (ensure you have enough space there)

if [ "$1" == "-h" ] || [ -z "$1" ]; then
    echo "Usage: `basename $0` [-h] [/path/to/store/dump/file/]"
    exit 0
fi

# load properties needed to dump RDS db
source unload_rds.properties

export PGPASSWORD=${ATL_JDBC_PASSWORD}

# -c=clean (ie drop db items before recreating them)
# -O means remove ownership, we will import all with the default owner of the new db
pg_dump --create --file=${1}rdsdump.sql --schema=public --host ${ATL_DB_HOST} --port=${ATL_DB_PORT} --username ${ATL_JDBC_USER} --no-owner ${ATL_DB_NAME}
