#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e


if [ "$1" == "--no-recurse" ]; then
        echo "Updating submodules non recursively\n"
        git submodule update --init
else
        echo "Updating submodules recursively\n"
        git submodule update --init --recursive
fi
